[package]
edition = "2021"
name = "hotwire"
version = "0.1.0"

[dependencies]
macroquad = "0.3"
ndarray = {version = "0.15", features = ["serde"]}
turbosql = {git = "https://github.com/trevyn/turbosql"}